version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch6
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9201:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:cached
    networks:
      # This is the name of the custom network being defined.
      company-chatbot:
        # This specifies an array of aliases for services within the network.
        # In this case, it assigns the alias chatbot.elasticsearch to services connected to the company_chatbot network.
        aliases:
          - es-local
          - es.search

volumes:
  elasticsearch:
    driver: local

networks:
  company-chatbot:
    name: 'chatbot'
    driver: bridge